spring:
  application:
    name: member-context
  datasource:
    url: jdbc:mysql://localhost:3306/member?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
#  kafka:
#    template:
#      default-topic: alarm-events
#    consumer:
#      bootstrap-servers: kafkaA:19092,kafkaB:19093,kafkaC:19094
#      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      group-id: alarm-events-listener-group
#      auto-offset-reset: latest
#    producer:
#      bootstrap-servers:
#        - localhost:9092,localhost:9093,localhost:9094
#        #- kafkaA:19092
#      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
server:
  port: 8080
  tomcat:
    mbeanregistry:
      enabled: true

encryption:
  key: pkl14nskhapj2n8j

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-components: always

