spring:
  application:
    name: check-in-request-MS
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://localhost:3306/place?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
  data:
    redis:
      host: localhost
      port: 6379
#  kafka:
#    topic: alarm-event
#    template:
#      default-topic: alarm-events
#    producer:
#      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
#      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#      properties:
#        acks: all
#        retries: 10
#        retry.backoff.ms: 1000
#    admin:
#      properties:
#        bootstrap.servers: localhost:9092,localhost:9093,localhost:9094

server:
  port: 8081
  tomcat:
    mbeanregistry:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-components: always

kakao-map-api:
  key: a0dc4e7625b15b5b4cef4e0a028119b3
