spring:
  application:
    name: check-in-request-MS
  datasource:
    url: jdbc:mysql://db:3306/place?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
          include: "*"
    health:
      show-components: always


kakao-map-api:
  key: a0dc4e7625b15b5b4cef4e0a028119b3
