package com.frontServer.infra.chunkUpload.exceptions;

public enum ChunkUploadError {

    CHUNK_FILE_NOT_EXISTS,
    CHUNK_DIR_CREATION_FAILED,
    UPLOD_DIR_CREATION_FAILED,
    WAIT_COPYING_INTERRUPTED,
    WAIT_COPYING_TIME_OUT,
    MERGE_FAILED,
    MERGE_IO_FAILED,
    FILE_COPY_FAILED,
    UPLOAD_COMPETION_CHECK_FAILED,
    CHUNK_SIZE_NOT_MATCH,
    CHUNK_FILE_SIZE_IO_FAILED;


}
